services:
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=Password123!
      - MARIADB_DATABASE=audiovault
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql:Z
  app:
    image: audiovault:0.2.1
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=root
      - DB_PASSWORD=Password123!
      - DB_NAME=audiovault
    volumes:
      - movies:/home/audiovault/movies
      - shows:/home/audiovault/shows
volumes:
  db-data:
  movies:
  shows:
