apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiovault-pv-claim
  namespace: audiovault
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi