name: CI pipeline

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
permissions:
  id-token: write
  contents: read

jobs:
  test_app:
    runs-on: ubuntu-24.04
    steps:
      - name: install needed system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libmariadb-dev gcc
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: install dependencies
        run: |
          python -m venv venv
          venv/bin/python -m pip install --upgrade pip
          venv/bin/pip install -r requirements.txt
      - name: run tests
        run: |
          sudo venv/bin/python -m pytest tests/test_content.py
          venv/bin/python -m pytest tests/test_miscellaneous.py
          venv/bin/python -m pytest tests/test_users.py

  build_and_push_docker_image:
    needs: test_app
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github_actions_ecr_access
      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} .
      - name: push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}